"""Proxy-aware engine probe (improvement plan 1.2 + 6).

Run ON the application server, through the corporate proxy. Checks each
engine's public search endpoint directly and reports pass/block, so the
enabled engine set in searxng/settings.yml matches measured reality instead
of assumption. With --apply, it regenerates the probe-managed `engines:`
section of settings.yml (between marker comments), annotating every entry
with the evidence and check date — the file stays the single source of
truth, regenerated rather than hand-edited.

Usage:
    python scripts/engine_probe.py                       # report only
    python scripts/engine_probe.py --apply               # rewrite settings.yml section
    python scripts/engine_probe.py --out probe_report.json
"""
import argparse
import asyncio
import json
import time
from dataclasses import asdict, dataclass
from pathlib import Path

import httpx

# genxng engine name -> a SERP-shaped endpoint that exercises the same host.
ENGINE_ENDPOINTS: dict[str, str] = {
    "google": "https://www.google.com/search?q=test",
    "bing": "https://www.bing.com/search?q=test",
    "duckduckgo": "https://html.duckduckgo.com/html/?q=test",
    "brave": "https://search.brave.com/search?q=test",
    "startpage": "https://www.startpage.com/sp/search?query=test",
    "qwant": "https://www.qwant.com/?q=test",
    "mojeek": "https://www.mojeek.com/search?q=test",
    "wikipedia": "https://en.wikipedia.org/w/index.php?search=test",
    "bing images": "https://www.bing.com/images/search?q=test",
    "bing news": "https://www.bing.com/news/search?q=test",
    "bing videos": "https://www.bing.com/videos/search?q=test",
}

MARKER_BEGIN = "# --- engine-probe: BEGIN (regenerated by scripts/engine_probe.py) ---"
MARKER_END = "# --- engine-probe: END ---"

BLOCK_BODY_MARKERS = ("unusual traffic", "captcha", "not a robot", "automated queries")
BLOCK_URL_MARKERS = ("/sorry", "captcha", "consent.google")


def classify_response(status: int, final_url: str, body_snippet: str) -> str:
    if status in (403, 429):
        return "block"
    if any(marker in final_url.lower() for marker in BLOCK_URL_MARKERS):
        return "block"
    if any(marker in body_snippet.lower() for marker in BLOCK_BODY_MARKERS):
        return "block"
    return "ok" if 200 <= status < 400 else "error"


@dataclass
class ProbeResult:
    engine: str
    url: str
    status: int  # 0 on network failure
    verdict: str  # ok | block | error


def render_engines_section(results: list[ProbeResult], checked: str) -> str:
    """The probe-managed `engines:` override block for settings.yml."""
    lines = [MARKER_BEGIN, "engines:"]
    for result in sorted(results, key=lambda r: r.engine):
        if result.verdict == "ok":
            comment = f"# passes proxy (checked {checked})"
            disabled = "false"
        else:
            detail = f"HTTP {result.status}" if result.status else "network failure"
            comment = f"# {result.verdict.upper()} via proxy: {detail} (checked {checked})"
            disabled = "true"
        lines.append(f"  - name: {result.engine}")
        lines.append(f"    disabled: {disabled}  {comment}")
    lines.append(MARKER_END)
    return "\n".join(lines)


def merge_into_settings(settings_text: str, section: str) -> str:
    """Replace the probe-managed block between markers, or append it."""
    if MARKER_BEGIN in settings_text and MARKER_END in settings_text:
        before = settings_text.split(MARKER_BEGIN)[0].rstrip("\n")
        after = settings_text.split(MARKER_END, 1)[1].lstrip("\n")
        merged = f"{before}\n\n{section}\n"
        if after:
            merged += f"{after}"
        return merged
    return settings_text.rstrip("\n") + f"\n\n{section}\n"


async def probe_all(client: httpx.AsyncClient) -> list[ProbeResult]:
    results: list[ProbeResult] = []
    for engine, url in ENGINE_ENDPOINTS.items():
        try:
            response = await client.get(url)
            verdict = classify_response(
                response.status_code, str(response.url), response.text[:2000]
            )
            results.append(ProbeResult(engine, url, response.status_code, verdict))
        except httpx.HTTPError:
            results.append(ProbeResult(engine, url, 0, "error"))
        await asyncio.sleep(1.0)  # be polite through the shared egress
    return results


async def run(args: argparse.Namespace) -> None:
    async with httpx.AsyncClient(
        timeout=args.timeout,
        follow_redirects=True,
        headers={"User-Agent": args.user_agent},
        trust_env=True,
    ) as client:
        results = await probe_all(client)

    print(f"{'engine':<14} {'status':<8} verdict")
    for result in results:
        status = result.status or "-"
        print(f"{result.engine:<14} {status!s:<8} {result.verdict}")

    checked = time.strftime("%Y-%m-%d")
    if args.out:
        with open(args.out, "w", encoding="utf-8") as fh:
            json.dump({"checked": checked, "results": [asdict(r) for r in results]}, fh,
                      indent=2)
        print(f"\nreport written to {args.out}")

    section = render_engines_section(results, checked)
    if args.apply:
        settings_path = Path(args.settings)
        merged = merge_into_settings(settings_path.read_text(encoding="utf-8"), section)
        settings_path.write_text(merged, encoding="utf-8", newline="\n")
        print(f"engines section regenerated in {settings_path} — restart the "
              "searxng container to apply")
    else:
        print("\nproposed engines section (use --apply to write it):\n")
        print(section)


def main() -> None:
    parser = argparse.ArgumentParser(description="proxy-aware engine probe")
    parser.add_argument("--settings", default="searxng/settings.yml")
    parser.add_argument("--apply", action="store_true",
                        help="regenerate the engines section in settings.yml")
    parser.add_argument("--out", default="", help="optional JSON report path")
    parser.add_argument("--timeout", type=float, default=15)
    parser.add_argument("--user-agent", default=(
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
        "(KHTML, like Gecko) Chrome/126.0 Safari/537.36"))
    asyncio.run(run(parser.parse_args()))


if __name__ == "__main__":
    main()
